### PR TITLE
Bugfix in treeReader, extra reader example removed

### PR DESCRIPTION
**Pull request by mexanick**

### CODE REVIEW

**Comment by sergueibaranov** [comment]
Hi,
please check what you defined:

gemdaq-testing/gemHwMonitor/src/common/gemHwMonitorWeb.cc
crateDevice_->setDeviceIPAddress("192.168.0.170");

SB

**Comment by sergueibaranov** [comment]
what is that?
gemdaq-testing/setup/scripts/glib_board_info_uhal.py
+sys.path.append('/home/mdalchen/gemdev/gem-daq-code/gemdaq-testing/setup/scripts/src')

**Comment by mexanick** [comment]
same as that
sys.path.append('/opt/gemdaq/firmware/testing/src')
hard-coded path. I’m not the author of this part of the project and not supposed to modify the code to include a env-related path instead of hardcoded. Initial code was only working at 904.

**Comment by sergueibaranov** [comment]
we need code at first for 904 !!! The beam test will be here. Sergey

**Pull request merged**
