### PR TITLE
release-v1

### PR DESCRIPTION
**Pull request by sergueibaranov**
Hi Jared, can you put in one line following printouts ?: 
Error:      0
Invalid:    0
RWMismatch: 0
errors while accessing registers:
Bad header:  0
Read errors: 0
Timeouts:    0
Controlhub errors: 8

We have ERRORS stream for DataParker. Which has been tested by 100 Hz with 16 VFATs

### CODE REVIEW

**Comment by jsturdy** [comment]
I don't understand what is included in this pull request, the request message is not at all descriptive enough.  Is the only addition the error stream?
Also, why is it important/necessary/desired to have the printout as a single line?

**Comment by sergueibaranov** [comment]
On 28.09.2015 13:59, Jared Sturdy wrote:
>
> I don't understand what is included in this pull request, the request 
> message is not at all descriptive enough. Is the only addition the 
> error stream?
> Also, why is it important/necessary/desired to have the printout as a 
> single line?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-gem-daq-project/gem-daq-code/pull/57#issuecomment-143723548>.
>
readability and compatibility are important

**Comment by jsturdy** [comment]
1) Right now, the output is quite readable. If you want all of that printout on one line, it would be unreadable (as is)
2) I don't understand what "incompatibility" you've encountered (and, in fact, doubt that there is one related to this)
3) Also you didn't respond to my primary comment, which concerned the lack of detail in your pull request.
The project has (for some time now) been at the level where a descriptive commit message and pull request message are absolutely necessary to understand what might change by inclusion.

**Comment by sergueibaranov** [comment]
> I don't understand what is included in this pull request, the request 
> message is not at all descriptive enough. Is the only addition the 
> error stream?
>

yes, the last pull request important for functionality of DataParker. 
You can see that before DataParker produces let say wrong distributions.

**Pull request closed without merging**
