### PR TITLE
The first multi links GEM event data format (one GEB event) has been made

### PR DESCRIPTION
**Pull request by sergueibaranov**

### CODE REVIEW

**Comment by jsturdy** [comment]
Merged pull request fails to compile:
make all
...
mkdir -p /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/lib/linux/x86_64_slc6
g++ -shared -fPIC -L/usr/lib64/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -o /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/lib/linux/x86_64_slc6/libgem_supervisor.so  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/version.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/VFAT2XMLParser.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/GEMTBUtil.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/ThresholdScan.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/ADCScan.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/LatencyScan.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMGLIBSupervisorWeb.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMSupervisor.o  /tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMSupervisorWeb.o  -L/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/lib/linux/x86_64_slc6 -L/opt/xdaq/lib -L/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemhardware/lib/linux/x86_64_slc6 -L/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemutils/lib/linux/x86_64_slc6 -L/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemreadout/lib/linux/x86_64_slc6 -L/opt/cactus/lib -L/tmp/sturdy/testing-releases/gem-daq-code/x86_64_slc6/lib -L/opt/xdaq/lib -llog4cplus -lconfig -lxcept -lboost_system -lcactus_uhal_uhal -lxerces-c -lgem_hw -lgem_utils -lgem_readout
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMGLIBSupervisorWeb.o:(.data+0x0): multiple definition of `gem::readout::slot'
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/ThresholdScan.o:(.data+0x0): first defined here
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMGLIBSupervisorWeb.o: In function `__gthread_active_p':
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/char_traits.h:250: multiple definition of `gem::readout::isFileRead'
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/ThresholdScan.o:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:62: first defined here
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMGLIBSupervisorWeb.o: In function `gem::readout::getSlotCfg()':
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemreadout/include/gem/readout/GEMslotContens.h:19: multiple definition of `gem::readout::getSlotCfg()'
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/ThresholdScan.o:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:62: first defined here
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/GEMGLIBSupervisorWeb.o: In function `gem::readout::GEBslotIndex(unsigned int const&)':
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemreadout/include/gem/readout/GEMslotContens.h:50: multiple definition of `gem::readout::GEBslotIndex(unsigned int const&)'
/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/src/linux/x86_64_slc6/tbutils/ThresholdScan.o:/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemreadout/include/gem/readout/GEMslotContens.h:50: first defined here
collect2: ld returned 1 exit status
make[2]: *** [/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/lib/linux/x86_64_slc6/libgem_supervisor.so] Error 1
make[2]: Leaving directory `/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor'
make[1]: *** [/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor/.loop] Error 2
make[1]: Leaving directory `/tmp/sturdy/testing-releases/gem-daq-code/gemdaq-testing/gemsupervisor'
make: *** [gemsupervisor] Error 2

**Comment by sergueibaranov** [comment]
I'll check tomorrow. In principal Threshold scan is out of time in the 
code and doesn't work in any case.
I'll put the latest code for Threshold scan from Felipe tomorrow and 
solve that problem.
   SB

**Comment by jsturdy** [comment]
See the following branch for a potential solution:
https://github.com/cms-gem-daq-project/gem-daq-code/tree/bugfix-multiple-definitions

Basically, putting many of the unassociated functions/variables from gem::readout into their own structs (a class with all public members in C++) and making the functions all static removes the multiple definitions link error.  This means there are two new structs, GEMDataAMCformat and GEMslotContents.
However, this may not be the best way to do this.  In principle I think it is the way to go, as the data format should be a class (with different parts having their own classes, see, e.g., https://github.com/cms-sw/cmssw/tree/CMSSW_7_6_X/DataFormats/FEDRawData/interface and https://github.com/cms-sw/cmssw/tree/CMSSW_7_6_X/DataFormats/FEDRawData/src) but we can discuss what would be the most correct way to do this within the language specification.

**Comment by sergueibaranov** [comment]
Hi Jared,
let use your solution. The latest code should replace the current 
"vfatDevice_->setDeviceBaseNode" in gemsupervisor/tbutils in any case.
I'll do that today and will check full functionality (GEMGLIBsupervisor 
& Thresholdscan).
     SB
PS. we can speak about best functionality any time. May be now more 
important to have needed functionality and than we can move in optimal 
code direction.

**Comment by sergueibaranov** [comment]
Ops, we have a ""Jeune genevois" today.  It's Holiday. We can move code 
debugging per one day.  SB

**Pull request merged**
