### PR TITLE
Data parker

### PR DESCRIPTION
**Pull request by mexanick**
* Added Data Parker readout from AMC13
* Some AMC13-related settings are hardcoded (e.g. IP address, slot mask)
* GEMUnpacker is working correctly, contains quite a lot of debug output
* LightDQM code hacked to be able work with a new data format, but a single GLIB/single chamber setup. Major updates foreseen soon.

### CODE REVIEW

**Comment by jsturdy** [comment]
This will require some cleverness to include... unfortunately, I didn't think of it at the time (due to my haste to move away from the old "data parker"), but it would have been better to keep the old "data parker" in it's whatever state, for backwards compatibility, and rather do what I had envisioned (but probably not made clear), which was to move towards the GEMReadoutApplication inherited classes (the minimal base class exists, and is already inheriting from the GEM application framework), e.g., AMC13Readout, GLIBReadout.  
 * How this would work in the ideal:
  * there is an application that reads raw data from some piece of hardware and puts it into a memory pool
  * this application then tells the file writer/event builder application that there is a new memory pool to process.
 * At the most basic level, AMC13Readout has the same functionality as this version of the "data parker" and GLIBReadout is the same as the previous version, and we bypass the memory pools for simplicity.

This all boils down to the fact that back in the day, I didn't think hard about the cases when the AMC13 readout would be possible or not, e.g., not if using the OH to do the triggering...
 * solution 1: remove the "data parker" updates, and whatever is associated, from this pull request (I suspect much of the DQM updates should be independent of the manner in which the data are collected, but perhaps doing the separation is a huge hassle)
  * solution 1b: move the code of this version of the "data parker" into the AMC13Readout application
  * solution 1c: move the code of old version of the "data parker" into the GLIBReadout application
  * at this point, things progress in the natural way, and are more "in framework"
 * solution 2: make a new branch off of release-v2, like release-v2-amc13, and merge this in there (probably the easiest, but still has some trickiness to ensure that other updates are carried forward into both branches... so this is far less than ideal)

**Comment by mexanick** [comment]
I see your point. I would then withdraw the pool request and reshuffle things. If we want to keep an ability to readout from GLIB buffer, I think we should go the path 1. Moreover, the lightDQM updates uses the proper values in AMC and chamber headers to parse the data structure, so we will need to add those in GLIB data parker (this is relatively easy, since we can readout only one or two chamber through GLIB, so we just put AMC13 number ==1, nAMC ==1 and will just need to care about number of GEB boards. As quickest ultimate solution, we can also stick to single GEB). I would like to do this before issuing a new pull request, since while I'm more/less OK to maintain two data parkers, I'm really against maintaining two different unpackers and lightDQM codes.
Just a side note: Robert and Malachi successfully parsed the new TTree structure with arbitrary number of electronic components and produced first plots. Now they're porting all the rest VFAT-related histogramming. Let me know if you are agree, then I can close the request.

**Comment by jsturdy** [comment]
Hi Misha, I totally agree, definitely no need to maintain multiple things!
So let's make the migration towards the "in-framework readout application"
Let me know if you want me to work on a specific part

**Comment by mexanick** [comment]
I think it would be great if you can pick one (AMC13 or GLIB) code and move it to the corresponding readout as example, so that I can follow your approach with second. 
I let you to choose what would be easier for you (well, AMC13 contains less code, but this is new code, while GLIB code is bigger, but you are probably more familiar with it).
If you migrate the GLIB parking code, I can also later modify it so that it will write correct values to headers parts used by unpacker and light dqm.

**Pull request closed without merging**
