### PR TITLE
The first Data Packer for OHv2

### PR DESCRIPTION
**Pull request by sergueibaranov**

### CODE REVIEW

**Comment by sergueibaranov** [comment]
The HW was missing, The last check was few days ago. The FIFO last week always full independently from XDAQ software at all.

**Comment by mexanick** [comment]
I still missing the logic of the multi-chip event selection. Could it be that proper code was overwritten by automated merge at some point? Sergey, could you please check this?

**Comment by jsturdy** [comment]
I'm going to reject this pull request based on Misha's observation as well as (primary reason) the lack of any description of what the pull request includes.
In the future, all pull requests lacking a summary of changes that is descriptive enough to audit will be rejected

**Comment by sergueibaranov** [comment]
I didn't see Misha's observation

**Pull request closed without merging**
